format = """
$time$status$cmd_duration$line_break\
${custom.github}${custom.heroku}$git_branch$directory$git_state${custom.git_log} $git_status$line_break\
$python$character\
"""

[time]
format = "[$time]($style)"
time_format = " %Y-%m-%d  %H:%M:%SZ"
utc_time_offset = "0"
disabled = false
style = ""

[status]
disabled = false
format = "[ $symbol $status]($style)"

[cmd_duration]
format = "[ 祥$duration]($style)"
style = "yellow"

[custom.github]
symbol = " "
command = 'git config --get-regexp remote github.com | sed -En "s/.+[/:]([^\]+)\/([^/]+)\.git$/\1\/\2\:/p"'
when = "git config --get-regexp remote github.com"
format = "[$symbol($output)]($syle)"

[custom.heroku]
symbol = " "
command = 'git config --get-regexp remote heroku.com | sed -En "s/.+\/([^/]+)\.git$/\1\:/p"'
when = "git config --get-regexp remote heroku.com"
format = "[$symbol($output)]($syle)"

[directory]
truncate_to_repo = true
home_symbol = " "
read_only = "  "
style = ""
repo_root_format = "[$path]($style)"
repo_root_style = ""

[directory.substitutions]
" /Dropbox" = " "

[git_branch]
symbol = ""
format = "[$symbol$branch]($style)"
style = "bold blue"

[custom.git_log]
command = 'git log master..HEAD --oneline | wc -l'
when = 'git log master..HEAD -1 --oneline | grep .'
symbol = " "
format = " [$symbol($output)]($style)"
style = "green"

[git_status]
format = '([$stashed$staged$conflicted$untracked$modified$renamed$deleted$ahead_behind](blue))'
deleted = "[  $count](blue) "
modified = "[ $count](blue) "
renamed = "[凜$count](blue) "
staged = "[ $count](green) "
stashed = "[ $count](yellow) "
untracked = "[ $count](blue) "
conflicted = "[ $count](red) "
ahead = "[ $count](green) "
behind = "[ $count](green) "
diverged = "[ $ahead_count](green) [ $behind_count](green) "
disabled = false

[python]
symbol = " "
format = "[$symbol$virtualenv]($style) "

